### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by danielnazer** [mozilla/rust-code-analysis#1005]
This Mozilla repository has been identified as lacking a LICENSE.md file. This repository does have licensing information in the README.md file. To make it easier for users (and scanning tools) to find licensing information please add a LICENSE.md file with that information to the root directory of the project.

Mozilla staff can access more information in our Software Licensing Runbook – search for “Licensing Runbook” in Confluence to find it.

If you have any questions you can contact Daniel Nazer who can be reached at dnazer on Mozilla email or Slack.

READMELIC-2023-01

**Comment by marco-c** [comment]
@danielnazer this repository uses two licenses, https://github.com/mozilla/rust-code-analysis#licenses, how can we handle that in a single LICENSE file so that users and scanning tools are able to understand it?

**Comment by danielnazer** [comment]
Good question - But since there are two licenses we probably can't construct the LICENSE.md file in a way that the scanning tools always pick it up correctly, so I think it's okay to just use the text you have in the Readme. I think generally even an "undefined" result for a scan will be better than nothing - will prompt whoever is reviewing to dig deeper.

**Comment by danielnazer** [comment]
Good question - But since there are two licenses we probably can't construct the LICENSE.md file in a way that the scanning tools always pick it up correctly, so I think it's okay to just use the text you have in the Readme. I think generally even an "undefined" result for a scan will be better than nothing - will prompt whoever is reviewing to dig deeper.
