### ISSUE TITLE
Tokei output compatibility

### ISSUE THREAD

**Issue by lu-zero** [mozilla/rust-code-analysis#104]
See [tokei](https://github.com/XAMPPRocky/tokei)

- [ ] tabular output 
- [x] json output
- [x] cbor/toml/yaml output

**Comment by Luni-4** [comment]
The tabular output would be difficult to read because `rust-code-analysis` has lots of metrics compared to `Tokei`. The `json` output is already implemented.

**Comment by lu-zero** [comment]
Having a table per-metric should solve the problem of having way too many columns I guess.

I do not have strong opinions in this regard, but would be nice to have a way to see the data from the cli w/out piping the json to something that formats it though.

**Comment by Luni-4** [comment]
> I do not have strong opinions in this regard, but would be nice to have a way to see the data from the cli w/out piping the json to something that formats it though.

Right, but for now the tabular option has low-priority compared to your third item :)

**Comment by Luni-4** [comment]
The tabular format presents a series of problems. 

Let `m` be the number of files in a directory, `n` the number of function spaces and `k` the number of tables. Let also suppose that each struct is represented by a table.

The final number of tables is then equal to: `m * n * k`
if the values of the three variables are pretty large, we would get an enormous output, difficult to analyze.

Possible approaches could be the following ones:
- Print only global metrics of each file
- Print only determined metrics for each file and function space
- Do not implement the tabular approach for `rust-cod-analysis`

**Comment by Luni-4** [comment]
Closed in favor of #163
