### ISSUE TITLE
rust-code-analysis-cli -m -p path/to/crate/src/lib.rs does nothing

### ISSUE THREAD

**Issue by jayvdb** [mozilla/rust-code-analysis#1087]
When I run `rust-code-analysis-cli -m -p path/to/crate/src/lib.rs` , nothing happens.

According to `rust-code-analysis-book/src/commands/metrics.md` this should do something.

I am using `master` with #1084 applied.

**Comment by jayvdb** [comment]
I have got as far with debugging as verifying that `fn metrics` in spaces.rs is processing the Rust code, but `func_space` is always false even when there are `fn`s in the file, and the nodes including some of type `function_item` so it looks like it is finding the fns.

**Comment by jayvdb** [comment]
Ok, the reason why I am getting no results is https://github.com/mozilla/rust-code-analysis/pull/1084 . 
When I use https://github.com/mozilla/rust-code-analysis/pull/1086 , I get results.

Still, the CLI should give some sort of result if no fns were found.

**Comment by marco-c** [comment]
Fixed by #1086.
