### ISSUE TITLE
Add an API endpoint that returns data about methods in a file

### ISSUE THREAD

**Issue by marco-c** [mozilla/rust-code-analysis#19]
Similarly to https://terryyin.github.io/lizard/.

**Comment by sauravkdubey** [comment]
Do I need to return the data of each file in a src directory

**Comment by sauravkdubey** [comment]
Can you specify the files of which the data needs to be returned ?

**Comment by marco-c** [comment]
@sauravkdubey the API endpoint would be generic, the file path is an input.

**Comment by sauravkdubey** [comment]
Okay, got it.
I will do it .

**Comment by calixteman** [comment]
@sauravkdubey I'm taking this bug since we need to implement AST traversal to compute the metrics.

**Comment by sauravkdubey** [comment]
@calixteman Should I implement the API endpoint issue ?

**Comment by calixteman** [comment]
@sauravkdubey the API endpoint is just a two liners patch, the main thing to do here is the metrics computation. So once, the computations are done we could then add the api endpoint.

**Comment by sauravkdubey** [comment]
@calixteman Sure, will do after once you fix the bug.

**Comment by calixteman** [comment]
Done:
https://github.com/mozilla/rust-code-analysis/commit/2e789f8b0fff462d56b6bd02b04241428eeb3461
