### ISSUE TITLE
Dump Halstead operators and operands

### ISSUE THREAD

**Issue by Luni-4** [mozilla/rust-code-analysis#232]
it would be helpful to add a flag to dump all `Halstead` operators and operands present in a code.

**Comment by marco-c** [comment]
Why do you need this?

**Comment by Luni-4** [comment]
https://github.com/SoftengPoliTo/Halstead-Metrics-Tool implemented a way to get them in order to check the operators present in a code. I guess it would be helpful having the same thing in `rust-code-analysis`. 

Could they be used for other metrics also?

**Comment by Luni-4** [comment]
Since this feature seems to have a low priority, we could hide it behind a Rust feature. In this way, only someone who is interested in this kind of code can use that
