### ISSUE TITLE
In the docs, generate subsections for "rust-code-analysis"

### ISSUE THREAD

**Issue by marco-c** [mozilla/rust-code-analysis#235]
Currently, "rust-code-analysis" has no subsections, so you have to scroll down to see what the contents are.

For example, I was looking for the list of metrics, and my first (wrong) instinct was to click on "Metrics" in the table of contents.
If there was a "Supported Metrics" subsection for "rust-code-analysis", I would have directly gone there.

**Comment by Luni-4** [comment]
https://github.com/rust-lang/mdBook/issues/167
https://github.com/rust-lang/mdBook/pull/1128

**Comment by Luni-4** [comment]
#236 is a temporary workaround for this issue
