### ISSUE TITLE
Calculate min and max for all metrics

### ISSUE THREAD

**Issue by marco-c** [mozilla/rust-code-analysis#410]
We are calculating sum and average, in some cases min and max could be useful too.

- [x] Cyclomatic
- [x] Nom
- [x] Loc
- [x] Cognitive
- [x] Nexit
- [x] Nargs
- [ ] Halstead
- [ ] Mi

**Comment by Luni-4** [comment]
`Halstead` and `Mi` metrics depend on other metrics it is not so fundamental computing min and max operators for them
