### ISSUE TITLE
Reduce Linux and Windows binaries size

### ISSUE THREAD

**Issue by Luni-4** [mozilla/rust-code-analysis#430]
It would be helpful to try to reduce the binaries size produced by `Rust` for each platform. In the CI there are still tasks that could allow these improvements, like the `package_windows_binary` one, that could be used to install additional software in a simpler way

Useful links for Linux:

https://github.com/johnthagen/min-sized-rust

Useful links for Windows

https://www.codeslow.com/2019/12/tiny-windows-executable-in-rust.html

https://github.com/mcountryman/min-sized-rust-windows

Another useful alternative, both for Linux and Windows, could be splitting debug symbols in separate files, but currently this possibility is blocked in https://github.com/rust-lang/rust/issues/72110

Alternative that makes use of external binaries both for Linux and Windows: http://www.sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html

**Comment by marco-c** [comment]
I don't think we'll want to split debug symbols in separate files, it makes things harder to handle for little benefit. It's useful for a generic customer facing software like Firefox, but it doesn't make much sense for us.
