### ISSUE TITLE
Explain how to build rust-code-analysis in the README

### ISSUE THREAD

**Issue by Luni-4** [mozilla/rust-code-analysis#443]
That would avoid having a dedicated page in the `mdBook`, making that knowledge more accessible to developers

**Comment by Luni-4** [comment]
We could also add some instructions to explain how to strip a binary if someone wants to do that

**Comment by marco-c** [comment]
> We could also add some instructions to explain how to strip a binary if someone wants to do that

That's too much of a corner case, 99,9% of people won't care about that for RCA.

**Comment by Luni-4** [comment]
Yeah, true. Perhaps only a simple remainder.

`RCA binaries are not stripped out`
