### ISSUE TITLE
Add support for Kotlin

### ISSUE THREAD

**Issue by marco-c** [mozilla/rust-code-analysis#577]
We can probably use https://github.com/fwcd/tree-sitter-kotlin or https://github.com/merico-dev/tree-sitter-kotlin

**Comment by Luni-4** [comment]
Kotlin has already been integrated in rust-code-analyis as grammar https://github.com/mozilla/rust-code-analysis/commit/c3921470f26880f4856ec4eee064f8470531f0d9
