### ISSUE TITLE
Update tree-sitter and grammars to version 0.20

### ISSUE THREAD

**Issue by marco-c** [mozilla/rust-code-analysis#674]

**Comment by dburriss** [comment]
Based on my issues adding `tree-sitter-c-sharp` I thought I would do a little look at the feasibility of rolling forward to 0.20.

- [ ] tree-sitter-java (version = "0.19.0" | tree-sitter = "0.19" | [PR](https://github.com/tree-sitter/tree-sitter-java/pull/86))
- [x] tree-sitter-typescript (version = "0.20.0" | tree-sitter = ">= 0.19, < 0.21")
- [x] tree-sitter-javascript (version = "0.20.0" | tree-sitter = ">= 0.19, < 0.21")
- [ ] tree-sitter-python (version = "0.19.0" | tree-sitter = ">= 0.19, < 0.21" | [PR](https://github.com/tree-sitter/tree-sitter-python/pull/120))
- [x] tree-sitter-rust (version = "0.20.1" | tree-sitter = "0.20" )

For c-sharp there is a [PR](https://github.com/tree-sitter/tree-sitter-c-sharp/pull/219) mentioned in #789 by the maintainer.

**Comment by marco-c** [comment]
The PRs are being ignored by the maintainers, we could use forks and specify dependencies as git repositories (https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories).
For example, for tree-sitter-python, we could specify `tree-sitter-python = { git = "https://github.com/Luni-4/tree-sitter-python", branch = "update-0.20" }`.

**Comment by dburriss** [comment]
@marco-c I was looking at #812 and was wondering if we have a final action plan here?
That PR looks like it is uncovering some good bugs uncovered by the upgrade (or some that were there already?).

I did notice Python points to its tree-sitter master and the other to a fork from @BrainBuzzer that is a work in progress.
In the merge, this would point to something more stable than master though.

I do want to ask though, what does 0.20 give us? Were there important security fixes, perf, features, that the project benefited from? Couldn't we settle on 0.19 until the situation improves with dependencies? This only makes sense if we think the situation CAN be improved. If it isn't something any of us can influence, then the forking strategy is the way to go.
