### ISSUE TITLE
Merge all dependencies bumps automatically

### ISSUE THREAD

**Issue by Luni-4** [mozilla/rust-code-analysis#90]
It would be useful to set [dependabot](https://dependabot.com/) such that it could automatically merge PRs that pass CI tests.

**Comment by Luni-4** [comment]
@calixteman 

What about this idea?

**Comment by calixteman** [comment]
I'm not a big fan in general of automatic merges.
Especially here we need to regenerate some rust files on tree-sitter-LANG changes.
So I think I would prefer not using auto-merge.

**Comment by Luni-4** [comment]
Oh, I see, thanks! I proposed this approach because there is a CI system, so it's possible to know in advance if a dependency breaks the code or not. But I understand your reasoning, so let's merge PRs manually :)
